### ISSUE TITLE
同じトゥートを続けてお気に入り・ブーストするとお気に入りのカウントがリセットされる

### ISSUE THREAD

**Issue by kaias1jp** [cutls/TheDesk#10]
![screenshot from 2018-12-19 20-32-54](https://user-images.githubusercontent.com/24523508/50217978-b9174600-03cd-11e9-9b76-81414e3ef38d.png)
あるトゥートを最初お気に入りにすると星の横に１が表示される。続けて同じトゥートをブーストすると、ブーストは１になるが星は０になる。星の色は明るく変わったまま。F5でリロードするとどちらも１になっている。

**Comment by cutls** [comment]
これは実装通りの挙動です。
トゥートをお気に入り登録するとお気に入り登録数を1増やし、ブーストのカウントを新たに取得して表示します。
逆に、
トゥートをブーストするとブーストのカウントを1増やし、お気に入り登録のカウントを新たに取得して表示します。
また、ブーストやお気に入りしても、すぐにはサーバーからの数値に反映されないため、続けてアクションをすると数値が減ることがあります。F5で取得し直すとどちらも最新の数値が表示されるため、再取得した値が正しい値となります。
これは、ブーストやお気に入りを解除した時も同様です。

**Comment by kaias1jp** [comment]
仕様とのこと、了解しました。クローズします。

**Comment by cutls** [comment]
勝手にMastodonの実装のせいにしちゃいましたが、実は何年も放置されたバグのせいだということです。TheDesk Usamin (18.11.1)で修正されています。
