### ISSUE TITLE
24.1.5 macOS Build Missing

### ISSUE THREAD

**Issue by krehel** [cutls/TheDesk#1017]
Hello!  Homebrew maintainer here 👋 

Looking if there will be a macOS build for `24.1.5` - looks like other platforms are available.

Also looks like a lot of the filenames are for `24.1.4` and the release title is `24.1.5`

Thanks!

**Comment by krehel** [comment]
Closing as the build for `24.1.6` contains a macOS version and it has been pulled in.

**Comment by cutls** [comment]
I'm sorry for causing you trouble

**Comment by krehel** [comment]
Absolutely no trouble at all @cutls and no apology needed!

Thank you for the development efforts!
