### ISSUE TITLE
Update Loop

### ISSUE THREAD

**Issue by bramnet** [cutls/TheDesk#1018]
### Describe the bug

The release 24.1.5 was released a few hours ago, but whenever I download and run the installer, TheDesk insists that it's still running 24.1.4 and prompts me to update again.

### To Reproduce

Open TheDesk and Get a prompt to update
Click on "Installer" and run the installer.
Wait for the installation completes
Open TheDesk back up, and see that the prompt to update appears again.

### Expected Behavior

Run Installer for the latest version
Open TheDesk after it finishes installing
Don't get prompted to update when opening unless there truly is a new update.

### Environment

- OS: Windows 10 Pro 22H2 (Build 19045.3570)
- Version: Anastasia (24.1.4 if you believe the update prompt, but I keep downloading and running the installer under 24.1.5 release)
- Your instance: social.veraciousnetwork.com

### Additional context

I've noticed under the 24.1.5 release, the version number was not updated for some of the builds. Maybe the builds themselves haven't been compiled for the new code or the version flag was not updated before release?

**Comment by cutls** [comment]
I mistook the release step of 24.1.5(and missing 24.1.5 for macOS). Please check 24.1.6 out.
