### ISSUE TITLE
macOSでyarn版のiTunes NowPlayingができない

### ISSUE THREAD

**Issue by cutls** [cutls/TheDesk#115]
Yarn版のやつ(Releaseにあるv18.10.1-beta, Travisビルド)でmacOSのiTunes NowPlayingができないらしい。npmではOKだった。

疑問
* フォント一覧は出る(つまりネイティブパッケージの話ではない)
  * というかyarnが問題でパッケージが入らないなら、他のパッケージも入らないのでUIが完全に崩れるよね
* itunes-npはasarUnpackとかいろいろ絡むししょうがないのか
* icu4cが絡む可能性(macOSのyarnがそれに依存。homebrewで入れようとすると勝手に入る)
* 個人のyarn環境の問題ならTravisでビルドしたやつが動かないのもおかしい
* 汚染されたyarn環境ではビルド済みのやつを動かそうとしてもエラるのか？それがasarUnpackの効果か？
* まだ1人のユーザーしか検証していないのでこの問題の一般度がわからない
* 何しろ実機がない。Kyash: cutls(冗談です)

**Comment by toneji** [comment]
僕の環境ではまだ解決できていませんが、macOSでyarnのみをインストールする方法がわかりましたので、書いておきます。
前提として、nodebrewでNode.jsがインストールされている必要があります。

$ brew install yarn --ignore-dependencies

これでicu4cはインストールされません。

Electronのビルドで使う場合、以下のコマンドも必要です。

$ yarn add electron-builder --dev

この時にyarnの最新版もインストールされます。
同時にいろんな依存関係もインストールされます。

しかし、この環境でビルドしても問題は解決しません。
これは現在の僕の環境が、macOS 10.15 Catalitaである可能性もあります。
iTunesの設計が大きく変わっています。
これについては、別のissueを立てます。

**Comment by cutls** [comment]
治った説があるので一旦Closeします
