### ISSUE TITLE
macOSでアプリの終了を止められる

### ISSUE THREAD

**Issue by kPherox** [cutls/TheDesk#134]
**再現方法**
1. quitイベントを発生させる
   - Command + Q
   - Dock MenuからQuit
   - MenubarからQuit
1. markersの送信
1. アプリが終了しない

**本来の挙動**
markersの送信後アプリが終了

**環境**
 - OS: macOS Mojave 10.14.6
 - バージョン: 18.11.0-dev

**追記**
修正案を2つ
1. 問題が発生する前と同じ挙動\
quitイベントが発生した時には終了、ウィンドウを閉じた時には終了させずに再度Dockから開ける\
https://github.com/cutls/TheDesk/commit/c3466d5c921780a6f70e1c0b075882b9e37ad02b
1. macOS以外と終了時の処理を統一
https://github.com/cutls/TheDesk/commit/d933eef8cc7a0f9df08f7603f84e218d4d55f2b1

**Comment by cutls** [comment]
うーん  
どっちの挙動がいいかはMacユーザーじゃないのでわからない

**Comment by kPherox** [comment]
以前 #47 で1の挙動にしたときはAppleのアプリやWhalebirdでの挙動を参考にして開けるようにしたけれど、viewを再構築したいときはリロードが備わってるしウィンドウだけ閉じてまた開くって使い方はあまり想定できないから、私は2の挙動にしてしまう方が楽だと思う

**Comment by toneji** [comment]
Macユーザーとしては2を支持します。
macOSの一般的なアプリの挙動として、処理が終わればアプリが終了するのが自然です。

昔はこういう設計に関して、Appleが書籍としてガイドラインを出していたのですが、今はありません。
そういう状況ですので、使っている人間にとって自然な挙動を選ぶしかないかなと思います。
