### ISSUE TITLE
macOS 10.15 Catalinaでミュージックアプリからのナウプレができない

### ISSUE THREAD

**Issue by toneji** [cutls/TheDesk#135]
macOS 10.15 Catalinaにアップデートしたところ、ミュージックアプリからのナウプレができなくなりました。

macOS 10.15 Catalinaから、旧iTunesが「ミュージック」「Podcast」「TV」という３つのアプリに機能が分離されました。
その影響だと思われますが、これまでできていたiTunesからのナウプレが機能しなくなっています。

確認のため、Catalina上でnpmでビルドしてみましたが、解決しません。
Spotifyからのナウプレは問題なく動作しています。

TheDeskそのものの問題ではないと思いますが、対応可能ならばありがたいです。

**Comment by cutls** [comment]
もはやiTunesですらないからなー
#115

**Comment by toneji** [comment]
困りましたね。
macOSのクライアントとして、１つ抜きんでてる機能だったのに…

**Comment by cutls** [comment]
他のiTunesの再生状況取得するアプリケーションは生きているのだろうか

**Comment by toneji** [comment]
> 他のiTunesの再生状況取得するアプリケーションは生きているのだろうか

僕が長く使っていた「Share Tunes 2」も使えなくなりました。

**Comment by toneji** [comment]
18.11.2をmacOS 10.15 Catalina上でnpmでビルドしたところ、ミュージックアプリでアートワーク付きでナウプレできることを確認しました。
対応ありがとうございました。
