### ISSUE TITLE
Linuxで英語OSの場合に一部文字がnullになる

### ISSUE THREAD

**Issue by kaias1jp** [cutls/TheDesk#14]
英語モードで起動するとトゥート画面で一部文字がnullになります。設定画面で一度日本語に切り替えてから英語に戻すとインスタンス名が表示されるので、初期状態の処理に日本語依存の部分がありそうです。
![screenshot from 2019-02-05 08-32-49](https://user-images.githubusercontent.com/24523508/52244710-323d0f00-2922-11e9-9691-62cef686b307.png)

**Comment by cutls** [comment]
ありがとうございます。
ついでにアイコン(Show profile of ...)も出てませんね
言語やOSに限らず、JavaScriptの依存関係的な問題な気がします(多分F5で治る)。
JSをまるごとちゃんとモジュール化してwebpackで依存関係解決してついでにまとめて幸せになりたい。
いろいろ調べて見ます。

**Comment by cutls** [comment]
新規で開くと必ずこうなるようです。
![image](https://user-images.githubusercontent.com/17561618/52248891-e09d8000-2933-11e9-9c17-242d25427752.png)
@kaias1jp ささいな修正でしたので修正版コミットを出しましたのでご確認おねがいします。また、クローズさせていただきます。

**Comment by kaias1jp** [comment]
お疲れ様です。修正が反映されていることを確認しました。アイコンについても問題ありませんでした。
