### ISSUE TITLE
Can't get image URLs

### ISSUE THREAD

**Issue by zergling-man** [cutls/TheDesk#162]
Describe the bug: There appears to be no way to get the URL of an image in a toot without opening the toot in an external browser.

**To Reproduce**
1. Right-click on image
2. Nothing happens.
3. Click on image to download full resolution.
4. Right-click it.
5. Nothing happens.
6. Try various other "more" inputs.
7. Receive disappointment.

**Expected behavior**
Right-clicking an image should provide a "copy URL" and/or "open image" context option.

**Environment**
 - OS: Manjaro 5.3.8
 - Version: Usamin (18.11.2)
 - Your instance: openweb.social

**Additional context**
This is a feature request disguised as a bug report.

**Comment by cutls** [comment]
OK, I'll add it to the next ver. ASAP. Thank you.

**Comment by cutls** [comment]
Fixed on 20.0.0 (Kawaii), check it out.

**Comment by zergling-man** [comment]
Nice, although the new button says "Copy URL of this toot" instead of "... this image".

**Comment by cutls** [comment]
Oh, my mistake. Sorry...
