### ISSUE TITLE
【要望】画像の添付時の422エラーへの対応について

### ISSUE THREAD

**Issue by kaias1jp** [cutls/TheDesk#17]
画像を添付するとき、ファイルサイズではなくpixel数(現状1024*1024？）が超えた画像を貼り付けると処理が戻ってこない。この場合、mastodonでは422エラーを返すので、エラーとして添付失敗にしてほしいです。
自分で実装考えてみましたが、リサイズ再投稿は死にそうになったのでそこまでは要望としては出しません。

**Comment by cutls** [comment]
次のバージョンで画像のリサイズを実装することにしましたのでよろしくお願いします
