### ISSUE TITLE
絵文字一覧の閉じるボタンが機能していない

### ISSUE THREAD

**Issue by Winding6636** [cutls/TheDesk#19]
投稿ボックスの絵文字一覧にて、"このボックスを閉じる"が機能していない。

なお、

- 投稿の[このボックスを閉じる]による連動
- [絵文字を挿入]ボタン

は問題なく機能しており、そこから開閉可能である。

---
 Win10/Miria(17.0.2)

**Comment by cutls** [comment]
@Winding6636  連絡ありがとうございます。修正いたしました。次回リリースで修正されます。また、Beta版がRelaseされた際にも変更は適用されています。
