### ISSUE TITLE
アクセストークンを直接入力してログインしたい

### ISSUE THREAD

**Issue by yuzulabo** [cutls/TheDesk#2]
TheDeskでは、ログインしたいインスタンスアドレスを入力するとElectron内のブラウザが起動してMastodonのログイン画面が現れる仕様だと思います。
ですが、これだと普段使用しているブラウザの認証情報が使用できず、(特に二段階認証を有効化していると)ログインが面倒なので、直接アクセストークンを入力する場所を作成するか、Chrome等普段使用しているブラウザで認証できるようにしていただく事は可能でしょうか。

よろしくお願いします。

**Comment by cutls** [comment]
Croudia版のCroudiaDeskのときも同様にどちらで開かせるかという議論がありました。
わかりました。実装します。

**Comment by cutls** [comment]
TheDesk Miho (ver.5)で実装しました。
ご指摘ありがとうございました。

**Comment by cutls** [comment]
アクセストークン指定についてもTheDesk Usamin(18.11.x)あたりで対応しました。
