### ISSUE TITLE
アンケートに関する選択バグ

### ISSUE THREAD

**Issue by cutls** [cutls/TheDesk#227]
原因はだいたい察しが付いてるけどとりあえずさっさと直して

> TheDesk、これはバグですか？になてり^^;
左カラムと右カラムとで同じアンケートが表示されている時、右カラムで項目を選択しても、左カラムにてハイライトされる。
(動画では第2カラムと第3カラムを使用したが、第1カラムと第2カラムでも発生した)
https://mstdn.maud.io/@dekisugi/103629788511402051

**Comment by dekisugi** [comment]
[@dekisugi@mstdn.maud.io](https://mstdn.maud.io/@dekisugi) です。一応環境を書いておきます。

**環境**
- OS: openSUSE Leap 15.1
- バージョン: 20.1.1, 20.1.2 (どちらもLinux zip版)
- インスタンス:
  - トゥート者: mstdn.maud.io, fedibird.com
  - 回答者: mstdn.maud.io

**Comment by cutls** [comment]
直した。あんなDOM指定してるから… @cutls は是非反省して悔い改めて
