### ISSUE TITLE
Snap version has unclosable popups

### ISSUE THREAD

**Issue by MichaelTunnell** [cutls/TheDesk#23]
I made a video to demonstrate what is going on, essentially when I start using it and when I change settings these popups happen and never close.

https://youtu.be/NzMcfcqBmfk

**Comment by cutls** [comment]
@MichaelTunnell I'm sorry to be late for notice your issue.
I will fix it soon, but you can close it to click "X" and "Until next version."

**Comment by MichaelTunnell** [comment]
I clicked X in the video repeatedly. The same thing for Until next version button.

**Comment by cutls** [comment]
New Snapstore version of TheDesk(17.2.0) is released. Please update it.

**Comment by cutls** [comment]
Closed because fixed.
