### ISSUE TITLE
ダウンロードリンク不正

### ISSUE THREAD

**Issue by mzch** [cutls/TheDesk#264]
v20.3.0 の .dmg ダウンロードリンクが不正です。v20.2.0 が落ちてきます。

**再現方法**
このようにするとバグが発生しました。
1. https://github.com/cutls/TheDesk/releases/download/v20.3.0/TheDesk-20.2.0.dmg をダウンロードする

**本来の挙動**
v20.3.0 をダウンロード

**環境**

**追記**

**Comment by cutls** [comment]
macOS版についてreleaseに上げるバージョンを間違えてしまいました。おそらく修正できたと思います。

**Comment by mzch** [comment]
確認しました。ありがとうございます。
