### ISSUE TITLE
一部のカスタム絵文字を含むユーザー名の表示が崩れる

### ISSUE THREAD

**Issue by AmaiSaeta** [cutls/TheDesk#342]
一部のカスタム絵文字を含むユーザー名を表示した際に崩れるようです。通常のテキストの部分が下にずれて表示されている模様。
![image](https://user-images.githubusercontent.com/345349/91868727-075a9e80-ecb0-11ea-8888-91b10b6f4d9d.png)
問題が確認できたのは、 https://fedibird.com/@ymd/104790228608750307 のtoot。ただし、カスタム絵文字全てで発生するという訳ではないようです。 https://mstdn.tamag.org/@nieein56/104790250733507530 が表示された際には、ユーザー名部分は問題なく表示されてたので。

**再現方法**
このようにするとバグが発生しました。
1. https://fedibird.com/@ymd/104790228608750307 がTLに流れた際に発生。
   + 該当tootの主がユーザー名を変えて、問題のカスタム絵文字を含まなくなると、現象が確認できなくなると思われます。

**本来の挙動**
![image](https://user-images.githubusercontent.com/345349/91870174-afbd3280-ecb1-11ea-8d0e-4238b4cf9041.png)
https://fedibird.com/@ymd/104790228608750307 をブラウザで表示した際と同様、通常のテキスト部分がずれる事なく表示される（キャプチャはFirefox80で表示した物）。

**環境**
 - OS: Fedora 32
 - バージョン: 21.0.5(Mayu)
TheDesk画面上部の「アプリケーション」から「TheDeskについて」で確認
- インスタンス: oransns.com

**Comment by cutls** [comment]
縦長なカスタム絵文字だと崩れるようです

**Comment by AmaiSaeta** [comment]
@cutls 対応ありがとうございます。因みに `object-fit` を `contain` ではなく `cover` にしたのは何故でしょう? [Mastodonの該当箇所](https://github.com/tootsuite/mastodon/blob/79305428a7c2bda311bc9d367a84acc28f569522/app/javascript/styles/mastodon/components.scss#L733) は `contain` みたいなのですが。

**Comment by cutls** [comment]
containだと必要以上に小さくなりなにの絵文字がわからないことがあるからです。
経験則上の話ですが、Fediverseによく流れる非長方形の絵文字を考えて、coverにしました。

**Comment by AmaiSaeta** [comment]
@cutls なるほど、回答を有り難うございます。

現master（ 4df390713c1dcde587a2ed98706873ee8dc323ca ）をビルドして、fixされている事を確認しましたのでcloseします。対応ありがとうございます！
