### ISSUE TITLE
Integrated TL won't update in version 21.1.1

### ISSUE THREAD

**Issue by zergling-man** [cutls/TheDesk#349]
Describe the bug: Integrated timeline loads, but does not update. For pleroma accounts, the TL icon shows red, as per "cannot connect to streaming API" that the tooltip notes.

**To Reproduce**
1. Run version 21.1.1
2. Create an integrated TL column on any account
3. Make a post, or compare with posts received on local/home TLs

**Expected behavior**
New posts should appear in integrated timeline

**Environment**
 - OS: Manjaro 5.7.19
 - Version: 21.1.1 (Mayu)
Check at 'Application,' 'About TheDesk' at top of the window.
- Your instance: openweb.social, social.quodverum.com, freespeechextremist.com

**Additional context**
Federated timeline works fine. I haven't tested any other types of TL.

**Comment by cutls** [comment]
I knew about it and has fixed it. So, check 21.2.2(latest)
If you cannot do although you updated it, please let me know again. Thank you.

**Comment by zergling-man** [comment]
Hmm, snapd tells me there isn't an update. Whatever, I'll assume it'll come through soon enough.

**Comment by cutls** [comment]
I think I published TheDesk 21.2.2 as latest/stable channel:  https://snapcraft.io/thedesk

**Comment by zergling-man** [comment]
...
Oh, I already have it installed. Just not yet running. Hurr durr.

**Comment by cutls** [comment]
Um, you are getting any trouble now?

**Comment by zergling-man** [comment]
A little bit, but it's just the usual "after several hours, need to refresh to reconnect" thing.
