### ISSUE TITLE
tl.jsで送信するJSONの不備

### ISSUE THREAD

**Issue by ponapalt** [cutls/TheDesk#353]
9/17 15:03時点のmasterの
app/js/tl/tl.js の295行目：

function stremaingSubscribe(type, acct_id, data, unsubscribe) 内の

mastodonBaseWs[domain].send(`{"type":"${command}","stream":"${stream}"`)

で投げるJSONの最後の中カッコが抜けています。
これが原因となり、各サーバ接続時にサーバ側のstreamingプロセスを落としてしまっているようです。

**Comment by cutls** [comment]
JSON.stringifyを使わなかったクズ人間の末路…

**Comment by ponapalt** [comment]
21.2.3で発生しなくなったことを確認したので、クローズします。
おつかれさまでした！
