### ISSUE TITLE
macOS版でiTunesのアートワークを投稿すると、ゴミ箱にアートワークがリカバーされる

### ISSUE THREAD

**Issue by toneji** [cutls/TheDesk#44]
macOSでiTunesのアートワークが投稿できるようになったのをとても重宝して使っています。

ただ、TheDeskを終了して、Macを再起動すると、必ずゴミ箱に「Recovered files」というフォルダが生成され、その中に投稿したアートワークがリカバーされています。

Macでこのようなファイルが生成されるのは、アプリが異常終了した場合が多いのですが、TheDeskは常に正常に終了しています。
実害はないので、すぐに対応してもらう必要はないのですが、一応お知らせしておきます。

参考にスクリーンショットを貼っておきます。
<img width="882" alt="スクリーンショット 2019-03-31 22 12 30" src="https://user-images.githubusercontent.com/5512055/55289631-bc29c580-5403-11e9-8b10-61214c22d46e.png">
<img width="882" alt="スクリーンショット 2019-03-31 22 12 57" src="https://user-images.githubusercontent.com/5512055/55289636-c6e45a80-5403-11e9-9ddf-f775fa47651d.png">

**Comment by cutls** [comment]
@kPherox 
多分仕様な気がします。アートワークを一時ファイルに書き出すみたいな処理をしていたと思うので、それがquit時にゴミ箱に入るのは、仕様上理解できます。
ゴミ箱から消すのはどうやるんでしょうね…調べてみます。

**Comment by kPherox** [comment]
TemporaryItemsに残したままにしている時の仕様ですね……

アプリ終了前に削除するようにしていないのが問題みたいです
https://discussions.apple.com/thread/7945692

**Comment by cutls** [comment]
macOSでの終了時はこれが実行されるので、この時にNode.jsのunlinkかなんかで消せたらいいんですけど…

https://github.com/cutls/TheDesk/blob/14c647ca4629d5fa46cc2d641c1b7436ae83789b/app/main.js#L75-L78

**Comment by toneji** [comment]
返信が遅くなりましたが、#55のマージで、上記の問題は解決されたようです。
とても使いやすくなりました。
いつもありがとうございます。
