### ISSUE TITLE
Enhancement: Open URL as toot

### ISSUE THREAD

**Issue by zergling-man** [cutls/TheDesk#446]
I'd like a function to attempt to open a given URL as a toot, on a specified account, without taking any other action.
Use-case is that I copy links and throw them to people on other platforms, then forget what they were so when they respond I have to open it to check context. Would be nice if I could throw it straight back to thedesk instead of to the browser (which may not be open at the time).
Would be even better if it could figure out if it's appeared in any of my TLs recently and just scroll it down appropriately, but that seems like it could be a massive pain to get working. (Especially with, eg. two identical TLs. Or, worse, two *different* TLs that both contained the post.)

**Comment by cutls** [comment]
You can use "Search". (it fetches the inputted URL via your Mastodon server, and may took 30 seconds...)
![image](https://user-images.githubusercontent.com/17561618/113241122-00991600-92e9-11eb-9933-0b7dfc06657a.png)

**Comment by zergling-man** [comment]
Ah, neat.
