### ISSUE TITLE
Emojis of flags not working

### ISSUE THREAD

**Issue by kPherox** [cutls/TheDesk#64]
旗の絵文字をうまく出力できない。添付した画像のように1文字のみになる（もう一度選ぶとうまく合った時に何かしらの国旗に変化はする	
![image](https://user-images.githubusercontent.com/13777426/57082417-a1fc4380-6d31-11e9-8631-ee4bb65b821e.png)

# env
macOS: 10.14.2
TheDesk: Usamin 18.3.1

**Comment by cutls** [comment]
確かにそうですね
なんででしょう…

**Comment by cutls** [comment]
Unicodeのプロじゃないのでなんもわからんけど、HEXの長さがフラッグ系は違うのかな？？？
ブラジルだとBRだけど 🇧🇷 、「B」用と「R」用に別々に変換しないといけないみたい(したらいけた)

**Comment by kPherox** [comment]
この問題見つけた時にいたサーバーでこの状態を話したらサロゲートペアのバグを踏んでるかもしれない…といったことを聞いたのでその辺ですかね（合成絵文字の項）
https://qiita.com/nonanona/items/b148c212ba7c24942e93#%E5%90%88%E6%88%90%E7%B5%B5%E6%96%87%E5%AD%97
