### ISSUE TITLE
[feature] Following multiple hashtags in one column.

### ISSUE THREAD

**Issue by M0IGA** [cutls/TheDesk#662]
Now any followed hashtag opens a separate column. Why do not allow to follow multiple hashtags in one column as the official web client has? see picture https://i.imgur.com/2tdF5xI.png

**Comment by cutls** [comment]
You have been already able to do it with clicking it: <img width="29" alt="Screen Shot 2022-05-07 at 12 20 47" src="https://user-images.githubusercontent.com/17561618/167236039-7dfe5e86-96ce-462d-8a34-4dd200d4fa3f.png">

<img width="363" alt="image" src="https://user-images.githubusercontent.com/17561618/167235989-86a45bdb-b916-42b7-8b23-a22231977580.png">

**Comment by M0IGA** [comment]
Great! It could be good to add that info to the official documentation. 
It's a little confusing how to add other hashtags. I tried to do this (#aprs #lora...etc) and it doesn't work.

Thanks for the quick response to my message.
