### ISSUE TITLE
Enhancement: Allow copy image media to clipboard

### ISSUE THREAD

**Issue by dowodenum** [cutls/TheDesk#715]
This is my flow in browser versions of Mastodon, if the meme isn't so good that I want to go through the steps to archive it.

Click to expand, right-click, copy image, switch tabs/windows, Ctrl+V.
Or hit ShareX "upload from clipboard" key to rehost and copy URL.

If supporting a full context menu is too much, maybe an extra button down by the zoom/rotate/link/save to accomplish the same thing:

![image](https://user-images.githubusercontent.com/57815700/187088512-eca48938-743b-4999-9c62-f839c0a7f160.png)

But I have no idea what ideogram you'd use for that.

Nice project though, I'm just beginning to check it out, maybe there is already a way to do what I'm wanting. It's sure faster than the standard frontend, but I guess browsers are usually pretty slow.

**Comment by cutls** [comment]
This feature will be added at v23.0.0, next update published today or tomorrow.
