### ISSUE TITLE
ブラウザ版のTheDeskを開くとNetlifyのPage Not Found が表示される

### ISSUE THREAD

**Issue by yu-kgr** [cutls/TheDesk#750]
ブラウザ版のTheDeskを開くとNetPage Not Found が表示され、アプリケーションが実行できない。

![image](https://user-images.githubusercontent.com/6540072/196069164-b19697c4-1680-48be-86c1-9521de87f685.png)

**再現方法**
このようにするとバグが発生しました。
1. https://thedesk.top/ でブラウザ版のタブを選択。
2. "ブラウザで試す" ボタンを選択すると上記Errorが発生しました

**本来の挙動**
- NetlifyのPage Not Foundページが表示されず、アプリケーションが利用できる

**環境**
 - OS: macOS Monterey
 - バージョン: ブラウザ版のため割愛（最新のmaster）
- インスタンス: ALL

**追記**
環境依存かと思い、異なるPC・ブラウザでも試してみましたが同様の問題が発生。
恐らくNetlify側でのなんらかの設定が起因してそうな空気を感じます。

1-2週間前から利用できなくなったので、それくらいから継続発生していそうです。

**Comment by cutls** [comment]
特にNetlifyの設定を変えたつもりは無いのですが、なぜかよく分からない場所にリダイレクトされてNot Foundが出ていました。修正しました。
