### ISSUE TITLE
Display Name cuts off when font size set lower than 11px

### ISSUE THREAD

**Issue by b-xb** [cutls/TheDesk#779]
Display Name cuts off at the bottom when font size set lower than 11px.

**To Reproduce**
1. Preferences -> System Preferences
2. Set font size to anything 11px or less
3. Bottom of the display name is now cut off on every Toot

**Expected behavior**
DIsplay name should not be cut off and should display fully.

**Environment**
 - OS: macOS Catalina 10.15.7
 - Version: 23.0.1
 - Screen size 13.3-inch (maximum resolution 2560 x 1600, was set to 1024X800 ubt now 1680x1050)

**Additional context**
I have adjusted the resolution on my screen to compensate but it would be nice to set the font as lower still, without breaking the theme.

**Comment by cutls** [comment]
I merged your PR ( #780 )
