### ISSUE TITLE
Broken Preferences options (23.0.2)

### ISSUE THREAD

**Issue by M0IGA** [cutls/TheDesk#788]
Broken Preferences. Most options is gone. Tested on Linux and MacOS.
I removed all configuration from the disk, and it's still the same problem.

screenshots
https://i.imgur.com/uZpjwun.png
https://i.imgur.com/ePWpMBg.png
https://i.imgur.com/RuQQxYA.png
https://i.imgur.com/mFUrygg.png

**Comment by cutls** [comment]
Yes, I also think TheDesk without tiresomely many config has no sense. I found some dependency update broke config builder. I will release fixed version ASAP.

**Comment by cutls** [comment]
Check 23.0.3. Enjoy!

**Comment by M0IGA** [comment]
Looks like everything came back to normal.

Thank you.
