### ISSUE TITLE
Mastodon v2.8.4にアップすると、通知カラムに何も通知されなくなる

### ISSUE THREAD

**Issue by toneji** [cutls/TheDesk#79]
箕面どんをMastodon v2.8.4にアップデートしたところ、通知カラムに一切通知が表示されなくなりました。いくら再読み込みしても、通知カラムだけベルが赤い状態です。

試しに、現段階のWIPのソースでビルドしてみましたが、症状は変わりません（Electron 5.0.1、node.js 12.0.0です）。
Guthubに公開されている「untagged-7a09954e3e9a8d8b9e02」をダウンロードして試しても同じでした。

ちなみにWebUIやWhalebird 2.7.2では問題ありません。
対応よろしくお願いします。

**Comment by cutls** [comment]
現行のTheDesk (18.4.0)でも、またWIPブランチの最新のTheDeskでも、minohdon.jpの通知を正しく表示できることを確認しています。
`Alt+Command+I`を押して、`Console`の中の**赤字になっているところ**を送ってください。

**Comment by toneji** [comment]
先ほど、通知カラムに通知が流れるようになりました。
使用しているのはWIPブランチの最新のTheDeskです。

Consoleのerrorの内容をスクショで送ります。
私の環境のみの問題だったのかもしれません。
<img width="550" alt="スクリーンショット 2019-05-26 18 01 23のコピー" src="https://user-images.githubusercontent.com/5512055/58379627-1cdb1600-7fe1-11e9-9ea6-eacf1e5e6abe.png">

**Comment by cutls** [comment]
その2つはすべての環境で出るものですね
自分の環境でも出ます。

とりあえず直ってよかったです。
