### ISSUE TITLE
[Fight] Struggle for NodeIntegration

### ISSUE THREAD

**Issue by cutls** [cutls/TheDesk#86]
TheDeskのレンダラプロセスではNodeIntegrationはtrueにしてはいけない(戒め)
不特定の情報を表示する場でさすがにNodeIntegrationはオンにできないよねーって

今考えてるのは、NodeIntegrationをオンにして、ウィンドウを表示させないプロセスを生成
Websocketサーバーを起動させる(そのウィンドウでは一切文字列を表示させてはいけない)
そして、WebsocketでTheDeskのレンダラと通信させる。
今までもipcでは文字列しか渡してないからWebsocketでも十分対処可能だろうけど、重くならないか心配(もとから重いのに)
NodeIntegrationを欲する機能

* NowPlaying(Spotify以外)
* ファイル選択
* 一部ダイアログ(alertやconfirmだけで対処してるのは除く)
* OSごとに処理を変えないといけないところ(process.osで見るところ)
* 画像編集(bmp変換)は多分もう無理

追記予定

もうだめ緒方智絵里誕生日おめでとう🎉

**Comment by cutls** [comment]
あとはあれだwebview
デフォルトオフにして、TweetDeck開けないとめっちゃ病むって人だけtrueにして再起動させるみたいなことをしないといけない

**Comment by kPherox** [comment]
nodeIntegration を`false`にすることでレンダラプロセスがメインプロセスと ipc で直接やり取りできなくなる問題、preload と`postMessage`を利用することで安全にやり取りできる形があるみたいなので nodeIntegration を true にしたレンダラプロセスを作る必要はないかもしれない

FYI: https://speakerdeck.com/masatokinugawa/electron-abusing-the-lack-of-context-isolation-curecon-ja

**Comment by cutls** [comment]
あとは外部から外部ソースのスクリプト実行されないようにするCSPのscript-srcくらいか
インラインでスクリプト実行させないためにはonclickを全部イベントに書き換える必要があるのでなかなか辛い(自分が悪い)

**Comment by cutls** [comment]
language.jsのリロードをIPC使わずに書く

**Comment by cutls** [comment]
リリース後に出したコミットもあるから18.6.0で完全対応というわけでもないが、とりあえず一段落したのでCloseします
