### ISSUE TITLE
「トゥート」を押下してもテキストボックスへのフォーカスに失敗する

### ISSUE THREAD

**Issue by windymelt** [cutls/TheDesk#860]
トゥートしようとしてもテキストボックスへのフォーカスに失敗しています。

**再現方法**
1. 「トゥート」をクリックする(もしくは、`X`を押下する)
2. トゥートダイアログが表示されるが、トゥート本文を入力するためのテキストボックスにフォーカスが当たらない

**本来の挙動**
本文入力用テキストボックスにフォーカスが遷移している

**環境**
 
OS
```
$ uname -a
Linux localhost.localdomain 5.14.21-150400.24.41-default #1 SMP PREEMPT_DYNAMIC Fri Jan 13 08:55:22 UTC 2023 (1d4442d) x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    openSUSE Leap 15.4
```

バージョン

22.1.1

![Screenshot from 2023-02-17 11-34-45](https://user-images.githubusercontent.com/1113940/219535148-324d602f-7063-47b8-927e-11663b584c3c.png)
 

- インスタンス: mstdn.takuya-a.net

**追記**

GNOME 3 / Waylandで実行しています。Snapでインストールしました。

**Comment by cutls** [comment]
この不具合は23.0.2で概ね修正されています。
長らくsnapでは古いバージョンしかインストールできませんでしたが、現在はedgeまたはstableチャネルから最新の24.0.10をインストールすることができるはずです。

**Comment by windymelt** [comment]
```sh
% snap refresh thedesk
thedesk 24.0.10 from Cutls P (cutls) refreshed
```

snap refreshを実行して解消しました。ありがとうございました 🙏🏻 🎉
