### ISSUE TITLE
bug:アクションメニューがマウスオーバー表示時に正常に使用できない

### ISSUE THREAD

**Issue by moz65535** [cutls/TheDesk#878]
「アクションメニューを非表示」設定を「マウスオーバーで表示」の設定において、
表示されたアクションメニューにマウスオーバーするとアクションメニューが閉じてしまい使用できない。

**再現方法**
1.「アクションメニューを非表示」を「マウスオーバーで表示」にする
2. 表示されているトゥートにマウスオーバーするとアクションメニューが表示される
3. そのまま表示されているアクションメニューにマウスオーバーさせようとすると、アクションメニューが閉じてしまう

**本来の挙動**
アクションメニューを表示する前の領域から出たときに閉じてしまう。
閉じる判定を、アクションメニューを開いたあとの領域まで含めて行うことが望ましい。

**環境**
 - OS: Windows10 Pro 22H2
 - バージョン: 24.0.10
- インスタンス: social.vivaldi.net

**Comment by cutls** [comment]
Also fixed when #877 was fixed
