### ISSUE TITLE
Homebrew cask? Update wording

### ISSUE THREAD

**Issue by mediaformat** [cutls/TheDesk#94]
> Was this software installed at Homebrew Cask? When select 'yes', any update was ignored.

If I understand the dialog correctly, Homebrew Cask users should select yes, because they will want to control updates themselves.

Just correcting the grammar, the message should say :
> Was this software installed with Homebrew Cask? Selecting 'yes', will ignore all updates.

But perhaps the dialog would be more useful to the average (non-Homebrew Cask) user if it stated:

> Do you want auto-updates?
> (Homebrew Cask users select 'No')

**Comment by cutls** [comment]
Yeah, I'll check it. Thank you for your issue.

**Comment by cutls** [comment]
I fixed it at the last update(TheDesk Usamin (18.6.5)), but I forgot to refer this issue to the commit:(
Thank you.
